# Site settings
title: Intervals
email: d.mesa91@uniandes.edu.co
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://intervals.xyz" # the base hostname & protocol for your site
twitter_username: jekyll
github_username:  jekyll

# Build settings
markdown: kramdown

# Custom collections (e.g. artists, reviews, news)
collections:
  artists:
    output: true
